### ISSUE TITLE
Enable HDR calculation

### ISSUE THREAD

**Issue by slhck** [Telecommunication-Telemedia-Assessment/siti-tools#8]
What we need:

- Keep the existing video read and SI/TI function
- Add a wrapper that accepts a new `mode` flag for choosing SDR, HDR10 or HLG input
- Create a new CLI that incorporates all options
- Get transfer functions: https://github.com/Telecommunication-Telemedia-Assessment/siti-tools/issues/7

Options:

- If SDR:
  - allow setting `range` to "limited" or "full"
  - allow specifying the `eotf_function`
    - BT.1886 (default) -> `bt1886`
    - Inverse sRGB -> `inverse_srgb`
    - Floating point gamma --> `gamma` (requires`eotf_gamma_value` too)
- If SDR or HLG:
  - allow setting `l_min`, `l_max` for display model
  - allow setting `l_w`, `l_b` for EOTF-HLG

------

Open (old) questions:

- How to meaningfully read different HDR content? Can ffmpeg do that?

**Comment by NabajeetBarman** [comment]
FFmpeg does have the capability to encode HDR videos, so should be useful here. One quick question if I missed: Is HDR actually going to have an effect on SI/TI values? I assume it is dependent on bit-depth but not sure about the transfer functions? Any literature I can refer to?

**Comment by slhck** [comment]
For sure it will have an effect. In the other issue, Lukas provides some details. But I'm pretty sure there is no research yet as to what that means perceptually.

**Comment by slhck** [comment]
The question is: do we want to have the user supply a YUV or Y4M file and provide further options for specifying HDR metadata, in which case we have to do a bit more validation work and cover different edge cases, or can we re-use a decoding function that gives us all we need already? I am afraid we have to do the work ourselves.

**Comment by NabajeetBarman** [comment]
> For sure it will have an effect. In the other issue, Lukas provides some details. But I'm pretty sure there is no research yet as to what that means perceptually.

I mean Sobel filter that we use just use the pixel values - which is (i assume) independent of the transfer function used in the HDR and rather depends on the bit-depth? But looking at the email discussion, it does seem to influence the pixel values, and hence the SI values - fair enough :)

**Comment by NabajeetBarman** [comment]
> The question is: do we want to have the user supply a YUV or Y4M file and provide further options for specifying HDR metadata, in which case we have to do a bit more validation work and cover different edge cases, or can we re-use a decoding function that gives us all we need already? I am afraid we have to do the work ourselves.

Ya, HDR in the picture does make this work quite complicated (more because of the limited tools and knowledge regarding HDR).

**Comment by slhck** [comment]
Will be fixed by #9

**Comment by slhck** [comment]
Implemented in cc2f687 and other commits.
